



spring:
  mvc:
    # JSP 설정
    view:
      prefix: /WEB-INF/
      suffix: .jsp
  
  # 타임리프 비활성화
  thymeleaf:
    enabled: false
  
  # DB설정
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
  
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect