spring:
  security:
    user:
      name: user
      password: testpw
  
  devtools:
    restart:
      # 로깅시 재시작 방지
      exclude: logs/**
  
logging:
  level:
    org:
      springframework:
        web:
          socket:
            config:
              WebSocketMessageBrokerStats: TRACE
